dist: trusty
sudo: true
services:
  - docker
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - DOCKER_IMAGE_NAME="q-table"
  - DOCKER_TAG=${TRAVIS_BRANCH/\//_}
script:
  - npm run build
  - npm run test
  - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
after_success:
  - echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin; docker
    tag $DOCKER_IMAGE_NAME:$DOCKER_TAG nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG; docker
    push nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG;
notifications:
  slack:
    secure: s6YBkURJyas8GOTp4AVYI5uhg8RW9lCslJhX+mvaLCqzFXYmGTF4fKR8YYsYyR9pvyiU3dbGTt6Ds+WkLUCbI2DVuYbZ4DUHpAUezm2UekdwCI2XncYrtp4o/Auo+rWKdKuIsAh9vl3Ga4BF1wrvSqJiICoGt+uT3BNWNR/6rc8/JAK19u53V4mmkd5wnwLUcl08iZjtIOjsBRbv5PpUL2z/bLXuxOWBbzX/bumnwEP5ez3Gp8peaDM68zRWTBhIqeHpT8xPdZ4IH1Uy2YA7FfgUC8SKs4ANp/tYEZcLC95yMMW/awWMSvVBpTVCb7oVBBwSTQwlkZf/3yrrjEPGokIQ2U7qyTC7+ATD1UTeevP1yO+A+O7J1yBx9Q0df4fQc4fswBFgasNVFL968jUttCqNIxOMXDrPeLHfMrsWCGXbVij/T//d3BoRJ95xNe9WSseZfywP8qg5eB/swzCXsLaQvsVwBSzXgAxnqC6isr7IzdIVHqfpRkTpWIf0S3cgptA7sxKyQ6l5xyxyRBgWtcyTZpfodnzvSPeHXvgMzXGP3hhVegaPXFlX51kf+8Y2OUBntkfa9kIkFhu3GrCaEcgmboVJiIu+4+lBrrLO5EBPebJNmFeAhQTl+FxSKXwLmYX3t86M96driB7cf0viYOgi+owicOtm17O93hOOtJI=
