dist: trusty
sudo: true
services:
- docker
language: node_js
node_js:
- '9.2'
install:
- npm install
before_script:
- DOCKER_IMAGE_NAME="q-table"
- DOCKER_TAG=$TRAVIS_BRANCH
script:
- npm run build
- docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG
  nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG; docker push nzzonline/$DOCKER_IMAGE_NAME:$DOCKER_TAG;
